version: '3.8'

services:
  backend:
    image: ${DOCKERHUB_USERNAME}/go-backend:latest
    build: ./backend
    environment:
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=skillpulse
    depends_on:
      database:
        condition: service_healthy

  frontend:
    image: ${DOCKERHUB_USERNAME}/nginx-frontend:latest
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  database:
    image: mysql:8.4
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=skillpulse
      - MYSQL_USER=rootuser
      - MYSQL_password=secret
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-psecret"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
