name: CD Workflow

on:
  workflow_run:
    workflows: ["CI Workflow"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Deploying Directly via Self-Hosted Runner
        run: |
          if [ ! -d "$HOME/skillpulse" ]; then
            echo "Directory does not exist. Creating it..."
            mkdir -p "$HOME/skillpulse"
          fi


          cd $HOME/skillpulse
          git pull origin main

          if [ ! -f .env ]; then
            echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" > .env
          fi

          docker-compose pull
          docker-compose up -d --remove-orphans
