name: CI

on:
  push:
    branches: main
    paths-ignore:
      - 'k8s/**'
      - 'docs/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push backend
        uses: docker/build-push-action@v7
        with:
          context: ./backend
          push: ${{ vars.DEPLOY_ENABLED == 'true' }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/skillpulse-backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/skillpulse-backend:${{ github.run_number }}

      - name: Build and push frontend
        uses: docker/build-push-action@v7
        with:
          context: ./frontend
          push: ${{ vars.DEPLOY_ENABLED == 'true' }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/skillpulse-frontend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/skillpulse-frontend:${{ github.run_number }}
