name: Deploying Directly via Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Deploying Directly via Self-Hosted Runner
        run: |
          
          
          mkdir -p "$HOME/skillpulse"
          cp -r . "$HOME/skillpulse/"
          cd "$HOME/skillpulse"
          
          
          docker compose down
          docker compose up -d --build
